#!/bin/bash
set +x
[[ "$JAVA_OPTS" =~ -Xm[s|x] ]] || JAVA_OPTS="$JAVA_OPTS -Xms64m -Xmx64m"
[[ "$JAVA_OPTS" =~ -Dfile.encoding ]] || JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

java $JAVA_OPTS -jar $SCRIPT_DIR/lib/${project.artifactId}-${project.version}-shaded.jar ${1+"$@"}
ex_code=$?

echo >&2
exit $ex_code